### ISSUE TITLE
Illegal instruction while installing Ruby 1.9.3-p194 on Ubuntu 14.04.1 LTS

### ISSUE THREAD

**Issue by remzicavdar** [sstephenson/ruby-build#605]
![Image of Yaktocat](http://drive.google.com/uc?export=view&id=0B_hJCqzHZ9C0QXFlRkd5QXdlN0U)

It works if I try to install 2.1.2

![Image of Yaktocat](http://drive.google.com/uc?export=view&id=0B_hJCqzHZ9C0OFhreE9pU3A5bVE)

**Comment by hsbt** [comment]
@remzicavdar No feedback, I close this.

**Comment by remzicavdar** [comment]
You could close this...

**Comment by hsbt** [comment]
@remzicavdar Ruby 1.9.3 is EOL now. Please use Ruby 2.0 or later. :bow:

**Comment by remzicavdar** [comment]
I will do :+1:
