### ISSUE TITLE
Ran into the _LIB_VERSION multiple def'n problem building tcltklib.so+libieee.a for 2.1.4

### ISSUE THREAD

**Issue by ericpromislow** [sstephenson/ruby-build#675]
```
$ rbenv install 2.1.4
...
checking ieeefp.h usability... no
checking ieeefp.h presence... no
checking for ieeefp.h... no
...
linking shared-object tcltklib.so
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libieee.a:(.data+0x0): multiple definition of `_LIB_VERSION'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libieee.a:(.data+0x0): first defined here
collect2: error: ld returned 1 exit status
```

I followed some suggestions in s/o, in particular Sam Ruby's 

```
sudo apt-get install g++ gcc make libc6-dev patch openssl ca-certificates libreadline6 libreadline6-dev curl zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev autoconf libc6-dev libgdbm-dev libncurses5-dev automake libtool bison pkg-config libffi-dev
```

but that didn't fix the problem.

This is on a recently installed Ubuntu 14.04.

I like the idea of shims. The idea of relying on scripts to do full builds, not so much.
Can I use the shim part of rvm while keeping my own separate installations of 
different versions of Ruby?

**Comment by mislav** [comment]
Hi @ericpromislow have you tried installing Ruby 2.1.6 or Ruby 2.2.2? Thanks

**Comment by ericpromislow** [comment]
I was able to build and install ruby 2.1.5 , so let's close this.

**Comment by ericpromislow** [comment]
I ran into this again trying to install a 1.9.3 build -- it's due to a conflict in a global variable named
LIB_VERSION in, I guess, libieee.a and some other library. Better to just build the version manually, copy it into ~/.rbenv/versions, and do `rbenv rehash` -- that is actually very cool.

I have yet to run into a flawless black-box build system.
