### ISSUE TITLE
Building rbx often fails due to OOM

### ISSUE THREAD

**Issue by dymk** [sstephenson/ruby-build#683]
Is there a way to restrict the number of parallel threads that ruby-build builds rbx with? I'm trying to install rbx on a box with not a lot of memory, so builds keep failing when ruby-build builds with four threads. I'd like to specify to build with only one or two threads.

**Comment by mislav** [comment]
I'm going to assume that this is not an issue for you anymore and close this. People finding this issue by search should try the `JOBS` environment variable to control the number of parallel jobs. I don't think we should edit ruby-build for this, though.
