### ISSUE TITLE
getting ruby-build usage example when trying to run rbenv install

### ISSUE THREAD

**Issue by mark-rightscale** [sstephenson/ruby-build#701]
hello, 
I am getting the ruby-build man-page when I try to run rbenv install 2.1.5
2.1.5 is in the list and I get the same error message for other builds as well.
It seems like it is passing incorrect arguments to ruby-build.

Ubuntu 14.04.1 LTS
rbenv 0.4.0-129-g7e0e85b
ruby-build 20141225-9-g73988db

thanks,
Mark

**Comment by mislav** [comment]
Hi Mark, sorry you're having trouble. Is `rbenv install 2.1.5` literally the exact command you're trying to run? Are you getting this help text as a result?

```
ruby-build 20141225-9-g73988db

Usage: ruby-build [-kvp] <definition> <prefix>
       ruby-build --definitions

  -k/--keep        Do not remove source tree after installation
  -v/--verbose     Verbose mode: print compilation status to stdout
  -p/--patch       Apply a patch from stdin before building
  --definitions    List all built-in definitions
```

Do you have any rbenv plugins? ``ls `rbenv root`/plugins``

**Comment by mark-rightscale** [comment]
yes that is the exact command and no other plugins. here is a cut/paste:
$ rbenv install 2.1.5
Usage: ruby-build [-kvp] <definition> <prefix>
       ruby-build --definitions

  -k/--keep        Do not remove source tree after installation
  -v/--verbose     Verbose mode: print compilation status to stdout
  -p/--patch       Apply a patch from stdin before building
  --definitions    List all built-in definitions

**Comment by mislav** [comment]
That is really bizarre. I'll try to reproduce, but in the meantime, try pasting me the output of `rbenv --debug install 2.1.5`. Use Gist if the output is very long.

**Comment by mark-rightscale** [comment]
Hello,

Thanks for looking into this.
~/.rbenv/plugins/ruby-build(master)$ rbenv --debug install 2.1.5
rbenv: no such command `--debug'

~/.rbenv(master)$ rbenv --debug install 2.1.5
rbenv: no such command `--debug'

I moved the dir and cloned both the ruby-build and rbenv repos again to see
if I would get anything different. Seems the same.
For some context, all was fine until I tried to upgrade to 2.1.5. It wasn't
in the list, so I did a pull on both repos and then I started getting the
man page for ruby-build.

Thanks,
Mark

**Comment by mislav** [comment]
If you cloned rbenv from master branch then you should have the latest version and the `--debug` flag should be effective. Since it's not, it seems like when you run `rbenv` it's not the master version, but the last 0.4.0 release.

Try `RBENV_DEBUG=1 rbenv install 2.1.5` instead.

**Comment by mark-rightscale** [comment]
Here is the output:
https://gist.github.com/mark-rightscale/4834c5c3b3eff1dfc27a

I installed a couple plugins this morning - rbenv-bundle-exec and
rbenv-gem-rehash.
They weren't there before.

the rbenv version is rbenv 0.4.0-129-g7e0e85b, I am on the master branch
and just did a git pull.

Thanks again,
Mark

**Comment by mislav** [comment]
You seem to have an outdated installation of both rbenv and rbenv-install in `/usr/lib/rbenv/libexec`. Please first investigate how that got there.

If you have installed rbenv from master in `~/.rbenv`, then `which -a rbenv` should show `/home/mark/.rbenv/bin/rbenv` and not `/usr/bin/rbenv`.

**Comment by mark-rightscale** [comment]
yeah, which -a gives me /usr/bin/rbenv
I'll figure that out. Thanks!

**Comment by mark-rightscale** [comment]
Thank you! Back in bidness.

**Comment by mislav** [comment]
You didn't tell us how you ended up with `/usr/bin/rbenv` in the first place. Manual install or some package manager?

**Comment by mark-rightscale** [comment]
It must have been through ubuntu software center.
I had help setting it up a year ago when I began ruby development, so I
forget the details.
It must have been fine until I hit a version not on the list for the older
repo which ubuntu is using and then I messed it up by cloning the repo and
trying to get that to install the new version.
Thanks again for your help.

**Comment by mislav** [comment]
Glad you solved it! :space_invader:
