### ISSUE TITLE
Let ruby-build try to build with the best compiler available to the system

### ISSUE THREAD

**Issue by grepwood** [sstephenson/ruby-build#706]
https://p8952.info/ruby/2014/12/12/benchmarking-ruby-with-gcc-and-clang.html
According to this benchmark, building with Clang is preferrable on a number of server-oriented Linux systems.
CentOS 6 has GCC 4.4 and Clang 3.4, the latter wins.
CentOS 7 has GCC 4.8 and Clang 3.5, the former wins.
Ubuntu 14.04 is in the same situation as CentOS 7.

**Comment by grepwood** [comment]
Pull request #707 fixes this issue for CentOS. Ubuntu and Debian will be added later.

**Comment by mislav** [comment]
Closing for the same reason as https://github.com/sstephenson/ruby-build/pull/707#issuecomment-70571673

Thanks for the suggestion, though! :dizzy:
