### ISSUE TITLE
Mac OSX Yosemite

### ISSUE THREAD

**Issue by TeckniX** [sstephenson/ruby-build#708]
Cannot install `rbenv install 2.2.0`
Error:
```
$ rbenv install 2.2.0
ruby-build: definition not found: 2.2.0

The following versions contain `2.2.0' in the name:
  2.2.0-dev
  2.2.0-dev
  2.2.0-preview1
  2.2.0-preview1
  rbx-2.2.0
  rbx-2.2.0

See all available versions with `rbenv install --list'.

$ brew upgrade ruby-build
Error: ruby-build 20150116 already installed
```

**Comment by mislav** [comment]
Can you check if you have ruby-build installed as an rbenv plugin (duplicate install):

```
ls `rbenv root`/plugins
```

If so, remove either the plugin or the Homebrew version. [See the wiki](https://github.com/sstephenson/ruby-build/wiki#updating-ruby-build)

**Comment by TeckniX** [comment]
Unfortunately I removed all and re-installed. It's very possible that the plugin was getting in the way.
Thanks for chiming in.
