### ISSUE TITLE
jruby 9.0.0.0-pre1 build fails

### ISSUE THREAD

**Issue by bl4ckn0de** [sstephenson/ruby-build#710]
Ubuntu 14.04
Oracle Java PPA enabled https://launchpad.net/~webupd8team/+archive/ubuntu/java
Oracle Java 8 installed

install process (i use ruby-build with rbenv) fails in my case with a (weird!?) error

```
➜  ~  rbenv install jruby-9.0.0.0-pre1
ERROR: Java 7 required. Please install a 1.7-compatible JRE.

BUILD FAILED (Ubuntu 14.04 using ruby-build 20150116-3-gad52e6e)

➜  ~  java -version
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
➜  ~  
```
so ... is required ONLY Java 7 or is a mistake ?

**Comment by mislav** [comment]
Thanks for reporting. Strange, because [the regex here should allow](https://github.com/sstephenson/ruby-build/blob/73988db2ae1cb0339f7e8fde959baf243f19f05e/bin/ruby-build#L689-696) "1.8" version. The "Java 7" constraint is only meant to disallow Java v1.6 and below

**Comment by bl4ckn0de** [comment]
problem found, if your Java install have JAVA_TOOL_OPTIONS defined then the first line in java -version don't give to you the version give to you the JAVA_TOOL_OPTIONS.

```
➜  ruby-build git:(master) ✗ java -version
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

in my case i have JAyatana java tool (global menus and more things between Java and Unity/Ubuntu) enabled, maybe a change, instead of `head -n1` use grep for the first line captured with version ?

```
➜  bayes git:(master) ✗ java -version 2>&1 | grep java\ version | head -1
java version "1.8.0_31"
```

 the problem happens in my Desktop machine, in server (without jayatana or other java things) works well.

**Comment by mislav** [comment]
Yes, thanks for identifying the problem.

**Comment by TheKidCoder** [comment]
I am still having this issue.

Ubuntu 14.10

Latest ruby-build from git.

```
deployer@rp-kevlar-app:~$ rbenv install jruby-9.0.0.0.pre2
ERROR: Java 7 required. Please install a 1.7-compatible JRE.

BUILD FAILED (Ubuntu 14.10 using ruby-build 20150506)
```

```
deployer@rp-kevlar-app:~$ java -version
openjdk version "1.8.0_40-internal"
OpenJDK Runtime Environment (build 1.8.0_40-internal-b09)
OpenJDK 64-Bit Server VM (build 25.40-b13, mixed mode)
```
