### ISSUE TITLE
Issue installing Ruby 2.1.2 with rbenv ruby-build on Mac OSX Yosemite (10.10.1)

### ISSUE THREAD

**Issue by shibbi** [sstephenson/ruby-build#712]
Hi, I'm trying to install 2.1.2 (required for an assignment) and am having issues. I searched existing issues similar to this and tried to prefix the "rbenv install 2.1.2" command with "CC=clang" or "CC=/usr/bin/gcc", and also tried installing version 2.1.3, but I still have problems. I also installed XCode command line tools and restarting computer/terminal but doing those didn't help either.

The issues all seem to be related to the make command and the files miniinit.o, dmydln.o, and main.o

Here are the full logs for each of the commands I tried.
rbenv install 2.1.2: https://gist.github.com/shibbi/170f5cb3ef71ac24a08d#file-log1
CC=/usr/bin/gcc rbenv install -f 2.1.2: https://gist.github.com/shibbi/170f5cb3ef71ac24a08d#file-log2
CC=/usr/bin/gcc rbenv install -f 2.1.3: https://gist.github.com/shibbi/170f5cb3ef71ac24a08d#file-log3
CC=clang rbenv install -f 2.1.2: https://gist.github.com/shibbi/170f5cb3ef71ac24a08d#file-log4

Any help is appreciated and I will provide additional information if it will help.

**Comment by mislav** [comment]
Hi, sorry you're having trouble. The best thing you could do is try one of the newer Ruby 2.1.x versions, such as 2.1.5. Some of the build problems were fixed in those version, and there are no feature differences between Ruby in 2.1.2 and 2.1.5, so it should be safe to use in your assignmnent. Let us know how it goes.

**Comment by mislav** [comment]
@shibbi Have you tried more recent Ruby versions, like 2.1.6? It should be safe to use in your assignment. Are you still getting errors?

The error messages "echo: no such file or directory" are worrisome. `echo` is a command that should exist on the system. Try `command echo yes` to see if it works.

I have no other suggestions right now how to help. Sorry :bow:

**Comment by shibbi** [comment]
@mislav Hi! Thanks for checking. I was able to fix this a few months ago, but I don't remember exactly what I did. I'll close the issue now.
