### ISSUE TITLE
Build failure - false alarm on CentOS

### ISSUE THREAD

**Issue by kliuless** [sstephenson/ruby-build#713]
Because of the way `compute_sha2` works, it causes `build_failed` to fire on CentOS even though no failure happened. `shasum` doesn't exist, so it tries openssl, but it runs `brew` which doesn't exist on Linux.
To reproduce, apply this patch, then try to install a ruby:

    diff --git a/bin/ruby-build b/bin/ruby-build
    index 46b7d84..11d1f05 100755
    --- a/bin/ruby-build
    +++ b/bin/ruby-build
    @@ -1166,2 +1166,7 @@ unset RUBYLIB
     trap build_failed ERR
    +echo $HAS_SHA2_SUPPORT
    +echo test | compute_sha2
    +echo "I'm still running!"
    +exit
    +
     mkdir -p "$BUILD_PATH"

You will see that SHA2 support exists, but the failure message appears. Then the script continues to run.

**Comment by mislav** [comment]
Thanks for the report! That explanation totally makes sense. What is your `bash --version`?

**Comment by mislav** [comment]
Possibly related: #561

**Comment by kliuless** [comment]
Thanks for the fix. Bash version is 3.2.25.
I did a grep and found other script occurrences of "brew". Might be good to audit these as well.

**Comment by mislav** [comment]
I did a quick audit but it seems that other occurences are OK. They either have `|| true` on them (like this fix) or they call out to an executable we're already sure it should be present on the system.
