### ISSUE TITLE
rbx-2.5.2 install fails on ubuntu 14.10 (missing ledit)

### ISSUE THREAD

**Issue by reza-naq** [sstephenson/ruby-build#717]
Hi there,
Since this is my first message here, I start with: "WELL DONE" to the contributors.
When I tried to install rbx-2.5.2 I got error message signaling that llvm was missing. I added it and the message gone. But next it compains about the lack of "ledit". This time when I add the thing it seems the compiler does not see it and keeps complaining the same way. 

Here is the log line around the erro
2: CXX vm/vm_thread_state.cpp
Build time: 177.009002593 seconds
1: LD vm/vm
/usr/bin/ld: cannot find -ledit
collect2: error: ld returned 1 exit status
Error: g++ -o vm/vm vm/artifacts/accessor_primitives.cpp.o vm/artifacts/arguments.cpp.o vm/artifacts/auxiliary_threads.c....

"/usr/bin/ld" exists on my system as a link to "ld.bfd", which exists and sits right next to "ld". A bit further under /usr/bin there's the so-called missing "ledit". 

Thanks

**Comment by Mazwak** [comment]
You are lacking "editline", not "ledit". Did you install all the requirements as documented ?
http://rubini.us/doc/en/getting-started/requirements/

**Comment by reza-naq** [comment]
Thanks Mazdav. 
I had installed lots of "ledit" related packages from ubunto repository and none of them let me compila the thing. After your advice I went for "editline" stuff and ... it worked! I installed "libedit-dev" and it's all working now.
