### ISSUE TITLE
Ruby 2.2.0 Fails during "Generating RI"

### ISSUE THREAD

**Issue by npazo** [sstephenson/ruby-build#721]
I suspect this is a server issue but I cannot find a solution. 2.1.5 installed just fine. And if I skip rdoc install, 2.2.0 works as well. Anyone have any ideas how to fix this issue?

```
Downloading ruby-2.2.0.tar.gz...                     
-> http://dqw8nmjcqpjn7.cloudfront.net/7671e394abfb5
d262fbcd3b27a71bf78737c7e9347fa21c39e58b0bb9c4840fc
Installing ruby-2.2.0...

BUILD FAILED (CentOS release 6.6 (Final) using ruby-
build 20150130-2-g8106d8f)

Inspect or clean up the working tree at /tmp/ruby-bu
ild.20150210151702.4709
Results logged to /tmp/ruby-build.20150210151702.470
9.log

Last 10 log lines:
 99% [961/967]  vm_dump.c
 99% [962/967]  vm_eval.c
 99% [963/967]  vm_exec.c
 99% [964/967]  vm_insnhelper.c
 99% [965/967]  vm_method.c
 99% [966/967]  vm_trace.c
100% [967/967]  vsnprintf.c

Generating RI format into /tmp/ruby-build.2015021015
1702.4709/ruby-2.2.0/.ext/rdoc...
make: *** [rdoc] Killed
```

**Comment by mislav** [comment]
Is it a virtual machine? Is it possible that it ran out of RAM or disk space on `/tmp` partition?

**Comment by npazo** [comment]
It is a VM. It just seems crazy that 2.2.0 is a problem and other else is. I'll look into that idea though.

**Comment by hsbt** [comment]
It seems to happen OOM killer. Please increase your RAM or add "--disable-install-doc" into configuration.

**Comment by adrivanrex** [comment]
I am also having this problem..
![45f6f63134b0f19393d0bcf76432eefb](https://cloud.githubusercontent.com/assets/2757277/6841921/6899a0cc-d3cc-11e4-8cc2-e28eae8a421d.png)

**Comment by hsbt** [comment]
@adrivanrex It's not related this issue. Please create new issue and attach build log.

**Comment by minimul** [comment]
I had this problem on a VM that was only 512mb RAM.
`CONFIGURE_OPTS="--disable-install-rdoc" rbenv install 2.2.2` enabled the install to work.

**Comment by mabras** [comment]
I had this also, and I increased the memory of my VM with Vagrant:

```
config.vm.provider "virtualbox" do |v|
  v.memory = 1024
end
```
