### ISSUE TITLE
2.2.0 doesn't compile on Suse 11.2 --- ./libffi-3.2.1/.libs/libffi.a: could not read symbols: Bad value

### ISSUE THREAD

**Issue by willsheppard** [sstephenson/ruby-build#725]
I haven't done any investigation of this error:

    ...
    compiling generator.c
    CCLD     libffi.la
    make[5]: Leaving directory `/tmp/ruby-build.20150227144425.3729/ruby-2.2.0/ext/fiddle/libffi-3.2.1'
    make[4]: Leaving directory `/tmp/ruby-build.20150227144425.3729/ruby-2.2.0/ext/fiddle/libffi-3.2.1'
    make[3]: Leaving directory `/tmp/ruby-build.20150227144425.3729/ruby-2.2.0/ext/fiddle/libffi-3.2.1'
    linking shared-object fiddle.so
    /usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: ./libffi-3.2.1/.libs/libffi.a(prep_cif.o): relocation R_X86_64_32 aga
    ./libffi-3.2.1/.libs/libffi.a: could not read symbols: Bad value
    collect2: ld returned 1 exit status
    make[2]: *** [../../.ext/x86_64-linux/fiddle.so] Error 1
    make[2]: Leaving directory `/tmp/ruby-build.20150227144425.3729/ruby-2.2.0/ext/fiddle'
    make[1]: *** [ext/fiddle/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    linking shared-object json/ext/generator.so
    make[2]: Leaving directory `/tmp/ruby-build.20150227144425.3729/ruby-2.2.0/ext/json/generator'
    make[1]: Leaving directory `/tmp/ruby-build.20150227144425.3729/ruby-2.2.0'
    make: *** [build-ext] Error 2

I did run this beforehand as suggested on the wiki:

    zypper install gcc automake gdbm-devel libffi-devel libyaml-devel openssl-devel ncurses-devel readline-devel zlib-devel

**Comment by p-run** [comment]
Same issue on debian testing/8:

<pre>
installing default libraries
make[2]: Leaving directory '/tmp/ruby-build.20150228223622.8951/ruby-2.2.0/ext/json'
make[2]: Entering directory '/tmp/ruby-build.20150228223622.8951/ruby-2.2.0/ext/json/generator'
compiling generator.c
  CPPAS    src/x86/unix64.lo
  CC       src/x86/ffi.lo
  CPPAS    src/x86/sysv.lo
  CCLD     libffi_convenience.la
  CCLD     libffi.la
make[5]: Leaving directory '/tmp/ruby-build.20150228223622.8951/ruby-2.2.0/ext/fiddle/libffi-3.2.1'
make[4]: Leaving directory '/tmp/ruby-build.20150228223622.8951/ruby-2.2.0/ext/fiddle/libffi-3.2.1'
make[3]: Leaving directory '/tmp/ruby-build.20150228223622.8951/ruby-2.2.0/ext/fiddle/libffi-3.2.1'
linking shared-object fiddle.so
/usr/bin/ld: ./libffi-3.2.1/.libs/libffi.a(raw_api.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
./libffi-3.2.1/.libs/libffi.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:325: recipe for target '../../.ext/x86_64-linux/fiddle.so' failed
make[2]: *** [../../.ext/x86_64-linux/fiddle.so] Error 1
make[2]: Leaving directory '/tmp/ruby-build.20150228223622.8951/ruby-2.2.0/ext/fiddle'
exts.mk:177: recipe for target 'ext/fiddle/all' failed
make[1]: *** [ext/fiddle/all] Error 2
make[1]: *** Waiting for unfinished jobs....
linking shared-object json/ext/generator.so
make[2]: Leaving directory '/tmp/ruby-build.20150228223622.8951/ruby-2.2.0/ext/json/generator'
make[1]: Leaving directory '/tmp/ruby-build.20150228223622.8951/ruby-2.2.0'
uncommon.mk:187: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
</pre>

**Comment by p-run** [comment]
Fix: install libffi-dev, then ruby does not try to build/install the bundled libffi.

**Comment by mislav** [comment]
Yes please see https://github.com/sstephenson/ruby-build/wiki#suggested-build-environment

**Comment by p-run** [comment]
When a bundled library fails to build, this sounds like a bug in the package to me.

**Comment by mislav** [comment]
Might be. I didn't know that ruby source distribution bundles libffi.

@hsbt: thoughts please?

**Comment by hsbt** [comment]
Can you try to build Ruby 2.2.1? We fixed bundled ffi configuration.

**Comment by jinglehp** [comment]
This was because the Makefile was trying to `linking shared-object fiddle.so', which needs `libffi.so` not `libffi.a`, however, the Makefile in fiddle was configured to link against `libffi.a`. changing `libffi.,a` to `libffi.so` in ext/fiddle/Makefile fix this problem.

**Comment by bfgobills** [comment]
I ran into this issue with 2.2.1 on RHEL 6 and was able to resolve it by
1) installing libffi-dev
2) commenting out the two references to the bundled libffi.a in the Makefile

This worked for me, however I wouldn't call myself an expert and thus I welcome opinions on this approach.

**Comment by p-run** [comment]
Installing ruby 2.2.1 without libffi-dev installed does not work for me.

<pre>
installing default libraries
make[2]: Leaving directory '/tmp/ruby-build.20150402100153.13061/ruby-2.2.1/ext/json'
make[2]: Entering directory '/tmp/ruby-build.20150402100153.13061/ruby-2.2.1/ext/json/generator'
compiling generator.c
  CC       src/x86/ffi64.lo
  CPPAS    src/x86/unix64.lo
  CC       src/x86/ffi.lo
  CPPAS    src/x86/sysv.lo
  CCLD     libffi_convenience.la
  CCLD     libffi.la
make[5]: Leaving directory '/tmp/ruby-build.20150402100153.13061/ruby-2.2.1/ext/fiddle/libffi-3.2.1'
make[4]: Leaving directory '/tmp/ruby-build.20150402100153.13061/ruby-2.2.1/ext/fiddle/libffi-3.2.1'
make[3]: Leaving directory '/tmp/ruby-build.20150402100153.13061/ruby-2.2.1/ext/fiddle/libffi-3.2.1'
linking shared-object fiddle.so
/usr/bin/ld: ./libffi-3.2.1/.libs/libffi.a(raw_api.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
./libffi-3.2.1/.libs/libffi.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:325: recipe for target '../../.ext/x86_64-linux/fiddle.so' failed
make[2]: *** [../../.ext/x86_64-linux/fiddle.so] Error 1
make[2]: Leaving directory '/tmp/ruby-build.20150402100153.13061/ruby-2.2.1/ext/fiddle'
exts.mk:177: recipe for target 'ext/fiddle/all' failed
make[1]: *** [ext/fiddle/all] Error 2
make[1]: *** Waiting for unfinished jobs....
linking shared-object json/ext/generator.so
make[2]: Leaving directory '/tmp/ruby-build.20150402100153.13061/ruby-2.2.1/ext/json/generator'
make[1]: Leaving directory '/tmp/ruby-build.20150402100153.13061/ruby-2.2.1'
uncommon.mk:189: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
</pre>

**Comment by hsbt** [comment]
Please try to Ruby 2.2.2

**Comment by hsbt** [comment]
@willsheppard If you still have some issue, Please reopen this.

**Comment by loadingvx** [comment]
You have a liba.a without -fPIC, buy it will never work ont x86_64.
a tricky way:
     you using *.o for you own.

gcc -fPIC path/liba.a mycode.o -o binary.
