### ISSUE TITLE
Ruby 2.2.1 fails because of typo in source: "LoadErroe"

### ISSUE THREAD

**Issue by liamdawson** [sstephenson/ruby-build#728]
When installing (Ubuntu 14.04 using ruby-build 20150303) 

    ./tool/rbinstall.rb:714:in `rescue in block in <main>': uninitialized constant LoadErroe (NameError)
	    from ./tool/rbinstall.rb:712:in `block in <main>'
	    from ./tool/rbinstall.rb:757:in `call'
	    from ./tool/rbinstall.rb:757:in `block in <main>'
	    from ./tool/rbinstall.rb:754:in `each'
	    from ./tool/rbinstall.rb:754:in `<main>'
    make: *** [do-install-all] Error 1

I'm assuming this is related to a cached version of the source that's a shade too old, otherwise, a patch or something will needed to be added to the definitions?

**Comment by liamdawson** [comment]
There's a known issue: https://redmine.ruby-lang.org/issues/10920

**Comment by liamdawson** [comment]
Here's a patch that seems to work: https://gist.github.com/liamdawson/5b20f45ae59755dcbc9d

(e.g. `rbenv install --patch 2.2.1 < 2.2.1-typo.patch`)

**Comment by fatim** [comment]
Both
rbenv install --patch 2.2.1 < /home/user/2.2.1-typo.patch
and
cat 2.2.1-typo.patch | rbenv install --patch 2.2.1
fail with
/home/user/.rbenv/plugins/ruby-build/bin/ruby-build: line 971: patch: command not found

**Comment by hsbt** [comment]
@liamdawson 

this issue is happen with missing zlib. Please install zlib to your environment, if you need to install bundled gems.

@fatim Please install patch command.

**Comment by liamdawson** [comment]
@hsbt How does a missing zlib relate to a typo in the source code? It's no longer an issue from my experience, btw.

**Comment by mislav** [comment]
@hsbt Reopening this because it's an unresolved issue that plagues ruby-build users. Could we auto-apply the patch for this?

**Comment by hsbt** [comment]
> Could we auto-apply the patch for this?

Not needed. This issue is only happen with zlib missing. I think zlib is included on suggested environment.
If user applied this patch with installation, they can not use rubygems and others.

**Comment by hsbt** [comment]
But I understand that this issue is unexpected behavior for ruby-build users.  I ask next release schedule of Ruby 2.2.2 to branch maintainer.

**Comment by hsbt** [comment]
We released Ruby 2.2.2 with fixing to this issue

**Comment by neohunter** [comment]
I know this is not related to this project, but I'm having the exact same issue with RVM, anyone knows how to apply the patch for that?
