### ISSUE TITLE
rbenv install 2.2.1 - recipe for target 'build-ext' failed (Arch Linux)

### ISSUE THREAD

**Issue by douyw** [sstephenson/ruby-build#731]
'rbenv install 2.2.1' on Arch Linux still does not work even libffi is installed. 

```
$ rbenv install --version
ruby-build 20150303

$ uname -a
Linux myarchlinux 3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux

$ rbenv install 2.2.1
Downloading ruby-2.2.1.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/5a4de38068eca8919cb087d338c0c2e3d72c9382c804fb27ab746e6c7819ab28
Installing ruby-2.2.1...

BUILD FAILED (Arch Linux using ruby-build 20150303)

Inspect or clean up the working tree at /tmp/ruby-build.20150318083414.15969
Results logged to /tmp/ruby-build.20150318083414.15969.log

Last 10 log lines:
make[2]: Leaving directory '/tmp/ruby-build.20150318083414.15969/ruby-2.2.1/ext/objspace'
installing default date_core libraries
installing default nkf libraries
linking shared-object date_core.so
make[2]: Leaving directory '/tmp/ruby-build.20150318083414.15969/ruby-2.2.1/ext/date'
linking shared-object nkf.so
make[2]: Leaving directory '/tmp/ruby-build.20150318083414.15969/ruby-2.2.1/ext/nkf'
make[1]: Leaving directory '/tmp/ruby-build.20150318083414.15969/ruby-2.2.1'
uncommon.mk:189: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
```
```
$ sudo pacman -Ss libffi
core/libffi 3.2.1-1 [installed]
    Portable foreign function interface library
```
from log file (/tmp/ruby-build.20150318083414.15969.log):
```
linking shared-object fiddle.so
/usr/bin/ld: ./libffi-3.2.1/.libs/libffi.a(raw_api.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
./libffi-3.2.1/.libs/libffi.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:325: recipe for target '../../.ext/x86_64-linux/fiddle.so' failed
make[2]: *** [../../.ext/x86_64-linux/fiddle.so] Error 1
make[2]: Leaving directory '/tmp/ruby-build.20150318083414.15969/ruby-2.2.1/ext/fiddle'
exts.mk:177: recipe for target 'ext/fiddle/all' failed
make[1]: *** [ext/fiddle/all] Error 2
```

**Comment by hsbt** [comment]
@douyw Thanks for your report. I got another fail report on other linux. I'll investigate this.

**Comment by mhw** [comment]
I got the same error when compiling on Ubuntu 12.04. I *think* I fixed it by installing libffi-dev and then running the install again.

**Comment by mijoharas** [comment]
Same thing on Ubuntu 12.04 as @mhw except not fixed by installing just the libffi-dev, but installing the rest of the packages recommended in the wiki seems to have done it: https://github.com/sstephenson/ruby-build/wiki

**Comment by jarl-dk** [comment]
I also ran into this problem on ubuntu 14.10, I also solved it by `sudo aptitude install libffi-dev`. Thanks @mhw

**Comment by douyw** [comment]
ruby 2.2.2 can be installed successfully.

```
$ rbenv install 2.2.2
Downloading ruby-2.2.2.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/5ffc0f317e429e6b29d4a98ac521c3ce65481bfd22a8cf845fa02a7b113d9b44
Installing ruby-2.2.2...
Installed ruby-2.2.2 to /home/fox/.rbenv/versions/2.2.2
```

**Comment by hsbt** [comment]
@douyw Thanks for your report!

**Comment by brentgsw** [comment]
I'm getting this same error trying to install 2.1.2 in manjaro(arch based).

**Comment by yuriyk** [comment]
I also ran into this problem on openSUSE Leap 42.1, I also solved it by
```
sudo zypper install libffi-devel-gcc5
```
Thanks @mhw

**Comment by Hellfar** [comment]
> ruby 2.2.2 can be installed successfully.
> 
> ```
> $ rbenv install 2.2.2
> Downloading ruby-2.2.2.tar.gz...
> -> http://dqw8nmjcqpjn7.cloudfront.net/5ffc0f317e429e6b29d4a98ac521c3ce65481bfd22a8cf845fa02a7b113d9b44
> Installing ruby-2.2.2...
> Installed ruby-2.2.2 to /home/fox/.rbenv/versions/2.2.2
> ```

Hi,

Having the exact same issue here for both `2.2.1` and `2.2.2` (also `libffi-dev` was already installed in my case).

The project I am trying to run does not specify any ruby version so actually trying to install any working version between 8 and 5 years ago.

`BUILD FAILED (LinuxMint 19.3 using ruby-build 20200401-11-g12af1c3)`
