### ISSUE TITLE
ruby 2.2.2 not availably

### ISSUE THREAD

**Issue by xiaods** [sstephenson/ruby-build#743]
please update asap.

**Comment by bsy** [comment]
cd ~/.rbenv/plugins/ruby-build && git pull

**Comment by xiaods** [comment]
@bsy i mean here: https://github.com/sstephenson/ruby-build/tree/master/share/ruby-build

i have not install rbenv.

**Comment by mislav** [comment]
@xiaods Ruby 2.2.2 is available. We have added it and cut a release. It's immediately available via git pull. If you used packages for ruby-build before, then you'll have to wait until the particular package gets updated with latest ruby-build version.

**Comment by xiaods** [comment]
@mislav cool
