### ISSUE TITLE
openssl not compiling for any ruby version

### ISSUE THREAD

**Issue by mturk2422** [sstephenson/ruby-build#746]
heres some info from the logs that might help someone else figure out what I'm doing wrong but I've been trying for days and can't figure out the problem….(also this is being done from my iPhone 4 iOS 7.1.2)

rbenv install 2.1.2      returns this….

```
Operating system: i686-apple-darwinDarwin Kernel Version 14.0.0: Thu May 15 23:18:01 PDT 2014; root:xnu-2423.10.71~1/RELEASE_ARM_S5L8930X
Configuring for darwin-i386-cc
...
Since you've disabled or enabled at least one algorithm, you need to do
the following before building:

	make depend

Configured for darwin-i386-cc.
making all in crypto...
make[1]: Entering directory `/private/var/tmp/ruby-build.20150414150616.20055/openssl-1.0.1m/crypto'
/usr/local/bin/perl ../util/mkbuildinf.pl "/usr/bin/arm-apple-darwin9-gcc-4.2.1 -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch i386 -O3 -fomit-frame-pointer -DL_ENDIAN -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM" "darwin-i386-cc" >buildinf.h
/usr/bin/arm-apple-darwin9-gcc-4.2.1 -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch i386 -O3 -fomit-frame-pointer -DL_ENDIAN -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -I/var/root/.rbenv/versions/2.1.2/include   -c -o cryptlib.o cryptlib.c
cc1: error: unrecognized command line option "-arch"
make[1]: *** [cryptlib.o] Error 1
make[1]: Leaving directory `/private/var/tmp/ruby-build.20150414150616.20055/openssl-1.0.1m/crypto'
make: *** [build_crypto] Error 1
 ```

**Comment by mturk2422** [comment]
im assuming its got something to do with this being configured for darwin-i386-cc and my OS being i686? I'm not sure though but i don't know what to do to fix it.

**Comment by mislav** [comment]
Strange; this is the first time I'm seeing this. Which exact OS version are you trying this on? I sincerely doubt that you're installing Ruby on your iPhone, as you mentioned. (Then I don't get the relevance of "this is being done from my iPhone 4".)

Also, which version is your `rbenv install --version`

**Comment by mturk2422** [comment]
I'm installing on my iPhone 4 which is running iOS 7.1.2. And when I ran ./config -t it would return my system as being i686 Darwin but configure for Darwin-i386-cc and give me 2minutes to run upstairs and grab the phone I do all this on....I just installed rbenv though so it should be the most up to date version 

Turk

**Comment by mturk2422** [comment]
Here's the rbenv version and the ./config -t output.....

**Comment by mislav** [comment]
I'm afraid I can't help you with installing Ruby on iOS since I don't have experience with it and it's probably not one of the platforms that Ruby maintainers support (since in its normal state it doesn't allow manually compiling software for it). You'll have to search the web for people who have completed this process and posted their workarounds.

**Comment by mislav** [comment]
I think iOS might already have OpenSSL pre-installed on the system. You can try using Apple's OpenSSL version with the option:

```sh
RUBY_CONFIGURE_OPTS=--with-openssl-dir=/path/to/openssl ruby-build ...
```

**Comment by hsbt** [comment]
We(ruby-core) do not support iOS environment. I think this issue should be close, because It's outside ruby-build issue.

**Comment by mislav** [comment]
Yes. Sorry, @mturk2422.
