### ISSUE TITLE
Error: "/Volumes/Macintosh: Not a directory"

### ISSUE THREAD

**Issue by bradbergeron-us** [sstephenson/ruby-build#748]
```
Installing ruby-2.2.2...
mkdir: /Volumes/Macintosh: Not a directory

##BUILD FAILED (OS X 10.10.3 using ruby-build 20150413)

###Inspect or clean up the working tree at /var/folders/58/fg59q9n577j9mfctgy63ylm00000gn/T/ruby-build.20150422063937.25340
Results logged to /var/folders/58/fg59q9n577j9mfctgy63ylm00000gn/T/ruby-build.20150422063937.25340.log

### Last 10 log lines:
Last-Modified: Mon, 13 Apr 2015 20:10:53 GMT
ETag: "326e99ddc75381c7b50c85f7089f3260"
Accept-Ranges: bytes
Server: AmazonS3
Age: 65639
X-Cache: Hit from cloudfront
Via: 1.1 0a17b6e7205e842c4e078772a70bf8c4.cloudfront.net (CloudFront)
X-Amz-Cf-Id: eo64Oxam2DxYbi3A20nu6FIyZYEVooU08ssb8yxy5gQrTLmHDX-4NA==

/var/folders/58/fg59q9n577j9mfctgy63ylm00000gn/T/ruby-build.20150422063937.25340/ruby-2.2.2 /var/folders/58/fg59q9n577j9mfctgy63ylm00000gn/T/ruby-build.20150422063937.25340 ~
```

**Comment by bradbergeron-us** [comment]
I think my problem may be similar to this perso's below

smace commented on Nov 20, 2014
I have found what was the problem, I'm using a SSD and a HDD in my MBP, / is mounted on my SSD and /user/home on my HDD, rbenv default directory is /user/home/.rbenv moving it to /usr/local/var/rbenv allowed to build ruby!

can you provide specific command line fix here as maybe this will help others in future

**Comment by mislav** [comment]
Thanks for reporting. I'm guessing this is because of a space in `/Volumes/Macintosh HD/` path that the installer is supposed to work with. See #385 and https://github.com/sstephenson/rbenv/issues/558

**Comment by mislav** [comment]
1. Is your `rbenv root` at default location? The default location is `~/.rbenv`
2. Can you tell us how your drives are mounted? `df`

**Comment by bradbergeron-us** [comment]
~
~
❯ cd ~/.rbenv

~/.rbenv
❯ ls
shims    versions

~/.rbenv
❯ cd ..

~
❯ df
Filesystem                                            Size   Used  Avail Capacity   iused     ifree %iused  Mounted on
/dev/disk2                                           111Gi   80Gi   30Gi    73%  21039717   7964953   73%   /
devfs                                                192Ki  192Ki    0Bi   100%       663         0  100%   /dev
/dev/disk1s2                                         698Gi  180Gi  518Gi    26%  47246327 135687415   26%   /Volumes/Macintosh HD
map -hosts                                             0Bi    0Bi    0Bi   100%         0         0  100%   /net
map auto_home                                          0Bi    0Bi    0Bi   100%         0         0  100%   /home
map -fstab                                             0Bi    0Bi    0Bi   100%         0         0  100%   /Network/Servers
//;AUTH=No%20User%20Authent@WDMyCloud.local./Public  1.8Ti  565Gi  1.2Ti    32% 148155667 321655423   32%   /Volumes/Public-1

**Comment by bradbergeron-us** [comment]
Tried changing names of hard drives and now can not even log in to my user profile 

###F********
ed
My data was structures so that I would launch into the SSD drive and had OSX installed on both al my application data was transferred onto SSD although I think technically my home folder was located on the HDD "MIcrosoft HD" and for some reason I've had Rbenv working correctly before maybe 2 months ago. 

Not sure what to do now, but if anyone can help I'd appreciate it.

**Comment by bradbergeron-us** [comment]
Update : logged in under guest and corrected path to my designated "login folder" with the new HDD name without spaces. 

##Root path to my login account is: 

*/Volumes/OSX_HD/users/#{login_name}*

**Comment by mislav** [comment]
I don't suggest you make any system changes. Instead, install rubies in a location that is not in your home folder, to avoid installing to "Macintosh HD". E.g.:

```sh
sudo mkdir -p /opt/rubies
sudo chown $USER:staff /opt/rubies
rm -rf ~/.rbenv/versions
ln -s /opt/rubies ~/.rbenv/versions
```

Now install Ruby version to `/opt/rubies` and they will be available as rbenv versions:

```sh
$ ruby-build 2.1.5 /opt/rubies/2.1.5
# (`rbenv install 2.1.5` might work as well; not sure)

$ rbenv global 2.1.5
```

**Comment by bradbergeron-us** [comment]
![](http://i.imgur.com/V0ak2MZ.jpg)

## Bad Substation error

Any suggestions as to what I can do from this point?

**Comment by bradbergeron-us** [comment]
![](http://cl.ly/al5d/o)

### Result 
When I attempted with Ruby-Build...

**Comment by bradbergeron-us** [comment]
[http://cl.ly/al5d/o]()

**Comment by bradbergeron-us** [comment]
Result with rbenv install

##[http://cl.ly/alMd](!failed)

**Comment by bradbergeron-us** [comment]
I disliked using RVM cause it was invasive on my path variables is there any hope for rbenv and Ruby-Build?

**Comment by bradbergeron-us** [comment]
## Saved -- Thank You!


![](https://s3.amazonaws.com/f.cl.ly/items/3v2M3b2s3V0V1y1J322J/Image%202015-04-23%20at%202.21.41%20PM.png)

**Comment by mislav** [comment]
Sorry you had trouble with my syntax (valid bash) in zsh. Maybe this would be better (in the future):

```sh
chown "${USER}:staff" /opt/rubies
```

**Comment by Serzhenka** [comment]
Thank you!
That's working for me too! :stuck_out_tongue_winking_eye:
Ruby-build 2.2.2, 10.10.3 OSX.
<code>
Installed ruby-2.2.2 to /opt/rubies/2.2.2
</code>

**Comment by mislav** [comment]
I've [added this caveat to our wiki](https://github.com/sstephenson/ruby-build/wiki#mkdir-volumesmacintosh-not-a-directory) so now I feel I can close this. Thanks everyone for participation.

**Comment by bradbergeron-us** [comment]
Yes that problem was awful, similar issue that should be added to Wiki is when the file **.rbenv.shim** gets in the way of the executable path. It has been an issue prior. But I think that should be added into the documenation as well.
