### ISSUE TITLE
Rubinius and llvm

### ISSUE THREAD

**Issue by 1337807** [sstephenson/ruby-build#767]
The `brew --prefix` command returns the path to the most recent version of llvm that would be installed, in my case `/usr/local/Cellar/llvm/3.6.1`.

Rubinius can only install with llvm 3.0-3.5 and even though 3.5 can be installed with brew as llvm35, the `brew --prefix` command will still return the path to 3.6.1 and the check on the lines below will fail, prompting the user to install llvm. If they do install it they will have the wrong version (3.6.1) and Rubinius will complain.

I managed to get Rubinius installed by hacking ruby-build locally to use `brew --prefix llvm35` and changed line 819 to look for `llvm-config-3.5` instead of `llvm-config`:

```
local llvm_prefix="$(brew --prefix llvm35 2>/dev/null || true)"
local llvm_config="${llvm_prefix}/bin/llvm-config-3.5"
``` 
https://github.com/sstephenson/ruby-build/blob/master/bin/ruby-build#L818-819

This is obviously not a long-term solution as I expect Rubinius will shortly support llvm 3.6.1 so I didn't PR the change, but I thought that an issue here might save somebody a bit of time until that upgrade comes along.

If you have an easier way to accomplish this please share it.

**Comment by mislav** [comment]
See #765 which I'm going to try wrap up soon.
