### ISSUE TITLE
Centos7 - Build Failed Missing OpenSSL lib 

### ISSUE THREAD

**Issue by cube1729** [sstephenson/ruby-build#774]
Hi, 

I'm having problems trying to get rbenv to install ruby on Centos7 (tried multiple version of ruby including 2.2.2, 2.1.6, 2.0.0-p645). The message I receive is "The Ruby openssl extension was not compiled. Missing openssl lib?" I have gone through the log and can only find openssl errors, searches have all recommended installing openssl-devel; however I already have this installed.

The Centos version is 7.1.1503 minimal install 64.
The following packages are installed through yum: git gcc openssl-devel libyaml-devel libffi-devel readline readline-devel zlib zlib-devel gdbm-devel ncurses-devel openssh-server ntp kernel-devel make wget bzip2 net-tools patch autoconf automake libtool bison curl sqlite-devel

I have version 0.4.0-151-g83ac0fb of rbenv and the latest ruby-build plugin. 

Does anyone have any idea why this fails? I have used rbenv on my Mac for a while and haven't ever had any issues so a bit stumped now trying to get this to work on Centos.

**Comment by mislav** [comment]
Sorry you're having issues :disappointed: 

It sounds like you did everything right. I have no idea why this is failing. Maybe you could paste us the full build log in a Gist?

**Comment by cube1729** [comment]
Thanks for your reply, as requested please see the full log.  

https://gist.github.com/fb5f9bde51901cd8be67.git

**Comment by mislav** [comment]
This is the key message:

```
configuring openssl
Failed to configure openssl. It will not be installed.
```

However I don't know why it failed to configure openssl. Maybe some build tool is missing?

**Comment by cube1729** [comment]
You were right the openssl build tools were missing, openssl-devel didn't install correctly. The log suggest it couldn't reach the upstream repo during the install. I didn't notice because I built the image from script.

I now have rbenv working correctly.
