### ISSUE TITLE
cannot install rbx-2.5.5 on OS X since homebrew llvm version is not supported

### ISSUE THREAD

**Issue by kaikuchn** [sstephenson/ruby-build#776]
I'm trying to install rubinius on OS X 10.10.3
I installed llvm via homebrew which to date is version 3.6.1 - the rubinius installation complains that this version is not supported (has to be one between 3.0 to 3.5).

I then removed llvm 3.6.1 and installed llvm 3.4 using `homebrew/versions`. However, [here](https://github.com/sstephenson/ruby-build/blob/e932d47195d76d6be9635a012056069e794039e0/bin/ruby-build#L818) you are using `brew --prefix llvm` to determine which llvm to use etc. So now the script is complaining that it needs llvm...

For the sake of completenes: when I have run `brew install llvm` and then I run `rbenv install rbx-2.5.5` I get
```
Downloading rubinius-2.5.5.tar.bz2...
-> http://dqw8nmjcqpjn7.cloudfront.net/217659849ca2c67322d24ce7167e760dc835f32a701ca6e558703914ca82d02f
Installing rubinius-2.5.5...

BUILD FAILED (OS X 10.10.3 using ruby-build 20150519)

Inspect or clean up the working tree at /var/folders/q6/2c98zk416q569hj9ddmc_v9h0000gn/T/ruby-build.20150623140047.37900
Results logged to /var/folders/q6/2c98zk416q569hj9ddmc_v9h0000gn/T/ruby-build.20150623140047.37900.log

Last 10 log lines:
Bundle complete! 5 Gemfile dependencies, 11 gems now installed.
Bundled gems are installed into ./vendor/bundle.
Checking clang: found
Checking clang++: found

Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': only LLVM 3.0-3.5 is supported
ABORT: unable to set up LLVM

Running 'configure' failed. Please check configure.log for more details.
```

Edit: Removed configure options I had passed at one point since they seem to do nothing... I could've sworn i got different output before..

**Comment by mislav** [comment]
I'm sorry that you're having trouble. This is going to get better with #765.

In the meantime, install LLVM 3.5 from homebrew/versions and use:

```sh
RUBY_CONFIGURE_OPTS="--llvm-config=/path/to/llvm-config"
```

**Comment by kaikuchn** [comment]
Thank you very much for the work-around! No need for you to apologize, had I known you guys are already working on a fix, I'd not have opened this issue. :)

Thanks for all the great work!

**Comment by mislav** [comment]
If it all worked, then you can close this issue :)
