### ISSUE TITLE
2.1.1 (and just 2.1.1) build failure on OS X 10.10.3

### ISSUE THREAD

**Issue by dafstone** [sstephenson/ruby-build#777]
I've been over the other threads on this topic and I'm making a new issue as the other reports don't seem to be as specific as mine.  (This is not a multiple file systems problem).  Sorry if this is considered a duplicate.

I'm running a on a brand new MBP with a fresh XCode install with Rbenv + Ruby-Build installed via homebrew.  Xcode Tools is installed.  I can build over versions (2.1.2 and 2.2.2) but just not 2.1.1.

Output of the build log as follows:

```
...

checking build system type... x86_64-apple-darwin14.3.0
checking host system type... x86_64-apple-darwin14.3.0
checking target system type... x86_64-apple-darwin14.3.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking how to run the C preprocessor... clang -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether clang needs -traditional... no
checking for ld... ld
checking whether the linker is GNU ld... no
checking whether clang -E accepts -o... yes
checking for real target cpu... x86_64
checking for ranlib... ranlib
checking for ar... ar
checking for as... as
checking for objdump... no
checking for gobjdump... no
checking for objcopy... no
checking for gobjcopy... no
checking for nm... nm
checking whether ln -s works... yes
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for dtrace... dtrace
checking for dot... no
checking for doxygen... no
checking for pkg-config... pkg-config
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for cd using physical directory... cd -P
checking whether CFLAGS is valid... yes
checking whether LDFLAGS is valid... no
configure: error: something wrong with LDFLAGS="-L/Users/stone/.rbenv/versions/2.1.1/lib "
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by chrismear** [comment]
I had a similar error when trying to install Ruby 2.1.0. I'm on OS X 10.10.3 and the compiler is Apple LLVM version 6.1.0, installed by Xcode 6.3.2.

A manual build Ruby 2.1.0 using the gcc-5 5.1.0 package from Homebrew was successful, which suggests that something in the config of the early Ruby 2.1.x releases is incompatible with the more recent Apple-provided compiler.

**Comment by mislav** [comment]
@dafstone You should upgrade to latest 2.1.x that fixes the build issues. The chance of the version bump breaking your app is very unlikely due to Ruby not changing functionality between patch releases.

A lot of people have noticed this, and it's unfortunate that it's failing, but we'd rather recommend that people upgrade than maintaining patches to apply to Ruby 2.1.1 to make it passing on OS X. Tell us if that worked so we can close this issue.

**Comment by dafstone** [comment]
Thanks guys - 

So, yes I upgraded to 2.1.x and that definitely took care of things.  This was actually legacy code I was running.  

I actually did this right away, but I thought I'd report the build error so that you're aware of it (which is sounds like you are). 

I haven't tried grabbing the gcc package separately and building that way, but I might try that if I have time for academic purposes.  If I do and have success I'll report it back here.  

Thanks!

**Comment by mislav** [comment]
Glad you solved it!

**Comment by ktimothy** [comment]
I had this problem with ruby 2.1.0, the solution was to create a directory from LDFLAGS variable (/Users/stone/.rbenv/versions/2.1.1/lib for this issue). I found the solution here http://www.reddit.com/r/ruby/comments/2m6p6n/ruby_215_is_released/
