### ISSUE TITLE
"C compiler cannot create executables" error trying to install Ruby (any version) on Fedora 22

### ISSUE THREAD

**Issue by GeoffreyEmerson** [sstephenson/ruby-build#779]
```
$ rbenv -v
rbenv 0.4.0-151-g83ac0fb
```

```
$ rbenv install 2.2.0
Downloading ruby-2.2.0.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/7671e394abfb5d262fbcd3b27a71bf78737c7e9347fa21c39e58b0bb9c4840fc
Installing ruby-2.2.0...

BUILD FAILED (Fedora 22 using ruby-build 20150519-13-g702b410)

Inspect or clean up the working tree at /tmp/ruby-build.20150704141301.2979
Results logged to /tmp/ruby-build.20150704141301.2979.log

Last 10 log lines:
config.guess already exists
config.sub already exists
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/ruby-build.20150704141301.2979/ruby-2.2.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
$
```

Relevant lines in the config.log:
```
configure:4146: checking whether the C compiler works
configure:4168: gcc  -O3 -Wno-error=shorten-64-to-32  -I/home/geoff/.rbenv/versions/2.2.0/include  -L/home/geoff/.rbenv/versions/2.2.0/lib  conftest.c  >&5
cc1: error: -Werror=shorten-64-to-32: no option -Wshorten-64-to-32
configure:4172: $? = 1
configure:4210: result: no
```

Full log at: https://gist.github.com/GeoffreyEmerson/3c8c315bd27766cb8f5d

While writing up this issue, I discovered a workaround from #319 which was `CC=gcc rbenv install 2.2.0` but I don't have clang installed, so that issue's cause seems to be different.

```
$ clang --version
bash: clang: command not found...
```

**Comment by mislav** [comment]
Did you [follow the instructions on the wiki](https://github.com/sstephenson/ruby-build/wiki) for Fedora and try again?

**Comment by GeoffreyEmerson** [comment]
@mislav Yes, I meant to include that in my post. The only thing in the wiki that seemed to apply was the recommended install packages, and I did that. 

`yum install -y gcc openssl-devel libyaml-devel libffi-devel readline-devel zlib-devel gdbm-devel ncurses-devel`

It might also be worth noting that Fedora now uses dnf by default, though that's not terribly important to this issue.

**Comment by GeoffreyEmerson** [comment]
UPDATE: After creating a fresh Fedora install, I was *not* able to reproduce this issue. 

The only other thing I can think of is that some previously installed package was interfering and triggering the same effect as the clang install.

Here's the list of installed packages on the system that was throwing errors: https://gist.github.com/GeoffreyEmerson/d45ac315432a9803c46b

**Comment by mislav** [comment]
Thanks for reporting. Glad you solved it.
