### ISSUE TITLE
Create a new release for jruby 9000

### ISSUE THREAD

**Issue by albertsj1** [sstephenson/ruby-build#793]
I see jruby 9000 is currently in the master branch for a couple of days.  Can you please create a new release so it can easily be installed via homebrew?

Thanks

**Comment by sferik** [comment]
I’ll try putting out a release this weekend. In the mean time, you can use the following command to install `master` via `homebrew`:

```sh
brew install ruby-build --HEAD
```

**Comment by jzinedine** [comment]
:+1:

**Comment by albertsj1** [comment]
Installing with --HEAD worked.  Thank you.

**Comment by donv** [comment]
@sferik thanks for the workaround.  It works well.  Still, could you push a new release?  The jruby-9.0.0.0 final release is a big thing :smile:  I'd be most grateful.
