### ISSUE TITLE
rbenv install 2.2.2 build failed on OSX 10.11 El Capitan

### ISSUE THREAD

**Issue by BoYanSTKO** [sstephenson/ruby-build#794]
I'm trying to install ruby 2.2.2 on El Capitan, but failed, I got the message:

```
Downloading ruby-2.2.2.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/5ffc0f317e429e6b29d4a98ac521c3ce65481bfd22a8cf845fa02a7b113d9b44
Installing ruby-2.2.2...

BUILD FAILED (OS X 10.11 using ruby-build 20150719)

Inspect or clean up the working tree at /var/folders/g_/4xc3skhj31g89q7z_czb4rx40000gn/T/ruby-build.20150723233128.20256
Results logged to /var/folders/g_/4xc3skhj31g89q7z_czb4rx40000gn/T/ruby-build.20150723233128.20256.log

Last 10 log lines:
    from /private/var/folders/g_/4xc3skhj31g89q7z_czb4rx40000gn/T/ruby-build.20150723233128.20256/ruby-2.2.2/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /private/var/folders/g_/4xc3skhj31g89q7z_czb4rx40000gn/T/ruby-build.20150723233128.20256/ruby-2.2.2/lib/rubygems.rb:556:in `install'
    from ./tool/rbinstall.rb:722:in `block (2 levels) in <main>'
    from ./tool/rbinstall.rb:721:in `each'
    from ./tool/rbinstall.rb:721:in `block in <main>'
    from ./tool/rbinstall.rb:757:in `call'
    from ./tool/rbinstall.rb:757:in `block in <main>'
    from ./tool/rbinstall.rb:754:in `each'
    from ./tool/rbinstall.rb:754:in `<main>'
make: *** [do-install-all] Error 1
```

I have homebrew and I updated my xcode to xcode7 beta.
I have installed command-line tools and I have updated them to the latest version as of today.

Does anyone know how to fix this? Thanks

**Comment by mislav** [comment]
Sorry you're having trouble. I haven't tried El Capitan yet. Can you paste the full build log as a gist?

**Comment by BoYanSTKO** [comment]
I solved the problem by upgrading openssl using brew upgrade openssl

**Comment by mislav** [comment]
Great! Thanks for letting us know.

**Comment by muhammad-saleh** [comment]
I guess I have a similar issue:


    ➜  ~  brew upgrade openssl
    Error: openssl 1.0.2d_1 already installed
    ➜  ~  rbenv install 2.0.0-p247
    Downloading ruby-2.0.0-p247.tar.gz...
    ->     https://dqw8nmjcqpjn7.cloudfront.net/3e71042872c77726409460e8647a2f304083a15ae0defe90d8000a69917e20d3
    Installing ruby-2.0.0-p247...

    BUILD FAILED (OS X 10.11 using ruby-build 20150928)

    Inspect or clean up the working tree at /var/folders/l1/lxlkz4ds1gg0n8lbt07rszwr0000gn/T/ruby- build.20151007102839.17005
    Results logged to /var/folders/l1/lxlkz4ds1gg0n8lbt07rszwr0000gn/T/ruby-build.20151007102839.17005.log

    Last 10 log lines:
	from ./tool/rbinstall.rb:185:in `makedirs'
	from ./tool/rbinstall.rb:289:in `prepare'
	from ./tool/rbinstall.rb:328:in `block in <main>'
	from ./tool/rbinstall.rb:758:in `call'
	from ./tool/rbinstall.rb:758:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:755:in `each'
	from ./tool/rbinstall.rb:755:in `block in <main>'
	from ./tool/rbinstall.rb:751:in `each'
	from ./tool/rbinstall.rb:751:in `<main>'
    make: *** [do-install-all] Error 1


Full log gist:
https://gist.github.com/muhammad-saleh/62f335b13e116153896c

**Comment by jeremy** [comment]
@muhammad-saleh check out the end of the log and you'll see
```
`mkdir': Permission denied - /Users/mohamedsaleh/.rbenv/versions (Errno::EACCES)
```
Suggesting that you have a file permissions problem. Fixing ownership or permissions of those files should fix. Perhaps you had done a `sudo …` setup against that rbenv root dir at some point?

Sledgehammer fix: `chown -R mohamedsaleh:admin ~/.rbenv`

**Comment by muhammad-saleh** [comment]
Fixed (Y) thanks a lot

**Comment by mislav** [comment]
@jeremy Thanks!
