### ISSUE TITLE
Not Able to intall ruby 2.2.2 on mac os x 10.10.3

### ISSUE THREAD

**Issue by KShambhavi** [sstephenson/ruby-build#795]
BUILD FAILED (OS X 10.10.3 using ruby-build 20150719)

Inspect or clean up the working tree at /var/folders/zd/22nn1rgs0wg77qjrr_bmkttm0000gn/T/ruby-build.20150729190928.754
Results logged to /var/folders/zd/22nn1rgs0wg77qjrr_bmkttm0000gn/T/ruby-build.20150729190928.754.log

Last 10 log lines:
                              minitest-5.4.3.gem
                              power_assert-0.2.2.gem
                              test-unit-3.0.8.gem
./tool/rbinstall.rb:728:in `chmod': Operation not permitted @ chmod_internal - /usr/local/rvm/gems/ruby-1.9.3-p194/ (Errno::EPERM)
	from ./tool/rbinstall.rb:728:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
make: *** [do-install-all] Error 1

**Comment by mislav** [comment]
Because the error message includes `/usr/local/rvm` path, I suspect that your problem is similar to https://github.com/sstephenson/ruby-build/issues/755#issuecomment-104806657

**Comment by KShambhavi** [comment]
Thank you for timely help. Removing rmv helped me install 2.2.2 without any errors. But even after rbenv global 2.2.2, ruby -v is giving me  "ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]"  
P.S : Before removing rmv ruby -v was giving 1.9.3.

Why is it not showing 2.2.2  inspite of the installation being run successfully without errors?

**Comment by mislav** [comment]
`ruby -v` will output the version which is currently selected with rbenv for this directory, which is not necessarily "2.2.2", but can be any other version. Please check with `rbenv version` for which version is currently selected.

To check if rbenv has been set up properly in the current shell, check `which ruby`. The output should be inside rbenv's `shims` directory.

**Comment by KShambhavi** [comment]
Thank you again. `which ruby` gives /usr/bin/ruby while while /rbenv/version says 2.2.2

Then added the line in .bash_profile as suggested in https://github.com/sstephenson/rbenv/issues/148

**Comment by KShambhavi** [comment]
Ruby 2.2.2 has been installed. Thank you :-)

**Comment by mislav** [comment]
I'm going to assume you've now set up rbenv correctly in your shell and that this can be closed. :+1:

**Comment by KShambhavi** [comment]
Yes I have successfully set up rbenv. Thank you.
