### ISSUE TITLE
unable to use local mirror

### ISSUE THREAD

**Issue by warroyo** [sstephenson/ruby-build#803]
I am attempting to use a local mirror and have set the `RUBY_BUILD_MIRROR_URL` environment variable. I noticed that when installing a ruby version it would always try to use `https://cache.ruby-lang.org` I took a  look through the ruby-build bash script and noticed the following lines.

````
 if [ -n "$RUBY_BUILD_MIRROR_URL" ]; then
      mirror_url="${RUBY_BUILD_MIRROR_URL}/$checksum"
    fi
````

in combination with this

````
 http head "$mirror_url" &&
    download_tarball "$mirror_url" "$package_filename" "$checksum" ||
    download_tarball "$package_url" "$package_filename" "$checksum"

````

this appends the checksum to the mirror url, which  always returns a 404 and prevents me from using my local mirror. What is the purpose of these lines? when I remove the appended checksum from the `mirror_url` I have no trouble installing.

**Comment by sstephenson** [comment]
The `RUBY_BUILD_MIRROR_URL` variable specifies a base URL for all packages, not the URL to a specific package. ruby-build computes the URL for a specific package by joining the SHA2 checksum of the package file to the base mirror URL.

https://github.com/sstephenson/ruby-build#package-download-mirrors

In other words, if you want to mirror the package files for Ruby 2.2.3, you'll need to save `ruby-2.2.3.tar.gz` to a file named `df795f2f99860745a416092a4004b016ccf77e8b82dec956b120f18bdc71edce`, and `openssl-1.0.1p.tar.gz` to a file named `bd5ee6803165c0fb60bbecbacacf244f1f90d2aa0d71353af610c29121e9b2f1`.

**Comment by warroyo** [comment]
So if a want to set my mirror to Artifactory, I would need to create a repo and set that as the `RUBY_BUILD_MIRROR_URL` and then save the tars as there checksums?

**Comment by mislav** [comment]
@warroyo To use a custom mirror, you want to ensure that the appropriate tarballs are available from download at URLs in format of `${RUBY_BUILD_MIRROR_URL}/${checksum}`

Any missing tarball at this URL will result in the original download location being used.

**Comment by warroyo** [comment]
i forgot to update, I have this working now
