### ISSUE TITLE
In build for 2.1.2, require 'fiddle' fails

### ISSUE THREAD

**Issue by trejkaz** [sstephenson/ruby-build#810]
I installed 2.1.2 using:

    rbenv install 2.1.2

The Ruby I ended up was [not able to `require 'fiddle'`](https://gist.github.com/trejkaz/1582aaccf0a917ff437c) because of an error, "Symbol not found: _ffi_type_double".

[A ticket I dug up somewhere else](https://github.com/CocoaPods/CocoaPods/issues/3571) suggests that extra flags made it work for their case. They were using 2.2.2, though, and when I tried the same flags for 2.1.2 I only got a broken Ruby that can't even launch irb.

I guess in the interim I can try to update to 2.2.2 and then try their workaround. Or I can go and find another way to load native libraries that already works.

**Comment by mislav** [comment]
I'm sorry you're having trouble with this. I googled for this error but it doesn't seem people are having this issue often. My ruby 2.1.2 (also built with ruby-build) can load fiddle without problem.

Can you try upgrading to latest 2.1.x version? It should be safe to update your apps to a newer patch release.

**Comment by trejkaz** [comment]
It's tricky. I installed rbenv from Homebrew and that was the latest version it had on there.
I guess I could graft in newer versions directly...

**Comment by mislav** [comment]
rbenv isn't responsible for building Ruby versions. Instead, the ruby-build project is in charge of that. So, if you used Homebrew to install that, you can `brew upgrade ruby-build` and then `rbenv install 2.1.6` and see if that has the same error. Thanks!

**Comment by trejkaz** [comment]
Yes, but like I was just saying,

    $ brew upgrade ruby-build
    Error: ruby-build 20150928 already installed

    $ rbenv install 2.1.6
    ruby-build: definition not found: 2.1.6

**Comment by mislav** [comment]
Sounds like you have double ruby-build installs. Do

    rm -rf `rbenv root`/plugins/ruby-build

and try again

**Comment by trejkaz** [comment]
OK, that works. And it looks like it does work on 2.1.6.

**Comment by mislav** [comment]
Thanks for the update!
