### ISSUE TITLE
BUILD FAILED (OS X 10.11 using ruby-build 20150928-2-g717a54c)

### ISSUE THREAD

**Issue by erwin16** [sstephenson/ruby-build#812]
after upgrade , cannot use rbenv  correctly anymore, Should I uninstall and reinstall it ?

yves@MacMini: ~ $ rbenv -v
rbenv 0.4.0
yves@MacMini: ~ $ rbenv install 2.2.3
Downloading ruby-2.2.3.tar.gz...
-> https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.3.tar.gz
error: failed to download ruby-2.2.3.tar.gz

BUILD FAILED (OS X 10.11 using ruby-build 20150928-2-g717a54c)

**Comment by erwin16** [comment]
I re-installed curl using brew ... and it's instilling fine now ...

**Comment by TangMonk** [comment]
still problem
