### ISSUE TITLE
compile ruby 2.2.0/2.3.0 with gcc < 4.4.0, -Wno-packed-bitfield-compat (includes solution)

### ISSUE THREAD

**Issue by ekr1** [sstephenson/ruby-build#822]
Hello,

there is a bug report against Ruby itself at https://bugs.ruby-lang.org/issues/10710 .

I am posting this issue here solely because that bug is 10 months old and has not been fixed from 2.2.0 to 2.3.0.

The bug manifests like this if a version of gcc < 4.4.0 is used:

```
> rbenv install 2.2.3
Downloading ruby-2.2.3.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/df795f2f99860745a416092a4004b016ccf77e8b82dec956b120f18bdc71edce
Installing ruby-2.2.3...

BUILD FAILED (Debian 5.0.10 using ruby-build 20151028-6-g01abf98)

Inspect or clean up the working tree at /tmp/ruby-build.20151106133207.27143
Results logged to /tmp/ruby-build.20151106133207.27143.log

Last 10 log lines:
eval.c: In function ‘ruby_cleanup’:
eval.c:185: warning: ‘_th’ may be used uninitialized in this function
eval.c:175: warning: ‘_th’ may be used uninitialized in this function
eval.c:165: warning: ‘_th’ may be used uninitialized in this function
At top level:
cc1: error: unrecognized command line option "-Wno-packed-bitfield-compat"
make: *** [proc.o] Error 1
At top level:
cc1: error: unrecognized command line option "-Wno-packed-bitfield-compat"
make: *** [eval.o] Error 1
```

A workaround with ruby-build is:

    > cat patch.txt  | rbenv install --patch 2.2.3
    Installing ruby-2.2.3...
    patching file configure
    patching file configure.in
    Installed ruby-2.2.3 to .../.rbenv/versions/2.2.3

With patch.txt being:

```
diff --git a/configure b/configure
*** a/configure 2015-08-18 16:05:00.000000000 +0200
--- b/configure 2015-11-06 13:42:27.000000000 +0100
***************
*** 7484,7490 ****
                 -Werror=implicit-function-declaration \
                 -Werror=division-by-zero \
                 -Werror=deprecated-declarations \
-                -Wno-packed-bitfield-compat \
                 $extra_warning \
                 ; do
        if test "$particular_werror_flags" != yes; then
--- 7484,7489 ----
diff -cw a/configure.in b/configure.in
*** a/configure.in      2015-05-19 21:06:36.000000000 +0200
--- b/configure.in      2015-11-06 13:41:44.000000000 +0100
***************
*** 803,809 ****
                 -Werror=implicit-function-declaration \
                 -Werror=division-by-zero \
                 -Werror=deprecated-declarations \
-                -Wno-packed-bitfield-compat \
                 $extra_warning \
                 ; do
        if test "$particular_werror_flags" != yes; then
--- 803,808 ----
```

I don't know if things like this are usually patched "behind the scenes" in ruby-build itself - if so, that would be nice of course. In that case one would likely only apply the patch if a version of gcc < 4.4.0 is detected (in my case it's 4.3.2, but according to https://www.gnu.org/software/gcc/gcc-4.4/changes.html it affects "many targets prior to GCC 4.4"). 

Note that my patch seems inoccuous to me; it _removes_ an option to suppress a warning that has been added with gcc 4.4.0. 

If this patch is not included in the official ruby-build, maybe the issue will at least spare folks half an hour figuring out how to create the `patch.txt` themselves.

**Comment by mislav** [comment]
Thanks for the heads-up! /cc @hsbt 

So far we haven't bundled patches with ruby-build like RVM does, but if there was ever a huge and persisting problem, I would be open to the idea. It certainly shouldn't be a big technical challenge. How pervasive is this problem, in your opinion? Is gcc 4.3 the default on Debian?

**Comment by hsbt** [comment]
Debian 5.0(lenny) status is already EOL[1]. ruby-build should not support this old distribution. I think better to introduce instruction of inline patch for EOL'ed distribution to FAQ.

[1]: https://wiki.debian.org/DebianLenny

**Comment by mislav** [comment]
@ekr1 Could you save the patch as a gist and share instructions for it on our wiki? https://github.com/sstephenson/ruby-build/wiki#troubleshooting

**Comment by ekr1** [comment]
@hsbt, thank you for checking the age of the components. It looks like gcc 4.4.0 is from 2009, so I guess it makes no sense at all to consider it in the ruby-build codebase itself. Debian stable is on 4.9.2 right now.

@mislav, I have updated the Wiki.

Guess we can close this then, thanks for helping me along. :)
