### ISSUE TITLE
How to deploy a package download mirror

### ISSUE THREAD

**Issue by cybertk** [sstephenson/ruby-build#823]
As **ruby-build** use its own mirror mechanism (url + md5_checksum), how can I deploy a mirror compatible with **ruby-build**? I already have a mirror of https://cache.ruby-lang.org

**Comment by mislav** [comment]
To host your own mirror on `http://example.com`, you need to make sure that downloads are available from URLs in format `http://example.com/<MD5>`. Then, do this before you run `ruby-build`:

```
export RUBY_BUILD_MIRROR_URL="http://example.com"
```

**Comment by mislav** [comment]
Sorry, I forgot to point out that checksums are not MD5, but SHA2. I've amended my above comment.

**Comment by cybertk** [comment]
How can I map sha2 to existing tarballs?
